# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from neurofly_core.rpc import neurofly_pb2 as neurofly__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in neurofly_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NeuroFlyStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/neurofly.NeuroFly/Info',
                request_serializer=neurofly__pb2.Empty.SerializeToString,
                response_deserializer=neurofly__pb2.InfoReply.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/neurofly.NeuroFly/Reset',
                request_serializer=neurofly__pb2.Empty.SerializeToString,
                response_deserializer=neurofly__pb2.Ack.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/neurofly.NeuroFly/Step',
                request_serializer=neurofly__pb2.StepRequest.SerializeToString,
                response_deserializer=neurofly__pb2.StepReply.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/neurofly.NeuroFly/Observe',
                request_serializer=neurofly__pb2.StepRequest.SerializeToString,
                response_deserializer=neurofly__pb2.StepReply.FromString,
                _registered_method=True)
        self.Stream = channel.stream_stream(
                '/neurofly.NeuroFly/Stream',
                request_serializer=neurofly__pb2.StepRequest.SerializeToString,
                response_deserializer=neurofly__pb2.StepReply.FromString,
                _registered_method=True)
        self.BodyStep = channel.unary_unary(
                '/neurofly.NeuroFly/BodyStep',
                request_serializer=neurofly__pb2.BodyRequest.SerializeToString,
                response_deserializer=neurofly__pb2.BodyReply.FromString,
                _registered_method=True)
        self.BodyStream = channel.stream_stream(
                '/neurofly.NeuroFly/BodyStream',
                request_serializer=neurofly__pb2.BodyRequest.SerializeToString,
                response_deserializer=neurofly__pb2.BodyReply.FromString,
                _registered_method=True)
        self.SetPolicy = channel.unary_unary(
                '/neurofly.NeuroFly/SetPolicy',
                request_serializer=neurofly__pb2.Policy.SerializeToString,
                response_deserializer=neurofly__pb2.Ack.FromString,
                _registered_method=True)
        self.Save = channel.unary_unary(
                '/neurofly.NeuroFly/Save',
                request_serializer=neurofly__pb2.SaveRequest.SerializeToString,
                response_deserializer=neurofly__pb2.SaveReply.FromString,
                _registered_method=True)
        self.Stimulate = channel.unary_unary(
                '/neurofly.NeuroFly/Stimulate',
                request_serializer=neurofly__pb2.Selection.SerializeToString,
                response_deserializer=neurofly__pb2.Count.FromString,
                _registered_method=True)
        self.Silence = channel.unary_unary(
                '/neurofly.NeuroFly/Silence',
                request_serializer=neurofly__pb2.Selection.SerializeToString,
                response_deserializer=neurofly__pb2.Count.FromString,
                _registered_method=True)
        self.Probe = channel.unary_unary(
                '/neurofly.NeuroFly/Probe',
                request_serializer=neurofly__pb2.Selection.SerializeToString,
                response_deserializer=neurofly__pb2.Count.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/neurofly.NeuroFly/Clear',
                request_serializer=neurofly__pb2.Empty.SerializeToString,
                response_deserializer=neurofly__pb2.Ack.FromString,
                _registered_method=True)
        self.Select = channel.unary_unary(
                '/neurofly.NeuroFly/Select',
                request_serializer=neurofly__pb2.Selection.SerializeToString,
                response_deserializer=neurofly__pb2.Indices.FromString,
                _registered_method=True)


class NeuroFlyServicer:
    """Missing associated documentation comment in .proto file."""

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """PC: controls (or features without a policy)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """PC: features, no policy involved
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request_iterator, context):
        """one reply per request, in order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BodyStep(self, request, context):
        """body: observation in, actuators out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BodyStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stimulate(self, request, context):
        """Selection.mv is the drive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Silence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Probe(self, request, context):
        """empty Selection turns the probe off
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Select(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeuroFlyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=neurofly__pb2.Empty.FromString,
                    response_serializer=neurofly__pb2.InfoReply.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=neurofly__pb2.Empty.FromString,
                    response_serializer=neurofly__pb2.Ack.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=neurofly__pb2.StepRequest.FromString,
                    response_serializer=neurofly__pb2.StepReply.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=neurofly__pb2.StepRequest.FromString,
                    response_serializer=neurofly__pb2.StepReply.SerializeToString,
            ),
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=neurofly__pb2.StepRequest.FromString,
                    response_serializer=neurofly__pb2.StepReply.SerializeToString,
            ),
            'BodyStep': grpc.unary_unary_rpc_method_handler(
                    servicer.BodyStep,
                    request_deserializer=neurofly__pb2.BodyRequest.FromString,
                    response_serializer=neurofly__pb2.BodyReply.SerializeToString,
            ),
            'BodyStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BodyStream,
                    request_deserializer=neurofly__pb2.BodyRequest.FromString,
                    response_serializer=neurofly__pb2.BodyReply.SerializeToString,
            ),
            'SetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPolicy,
                    request_deserializer=neurofly__pb2.Policy.FromString,
                    response_serializer=neurofly__pb2.Ack.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=neurofly__pb2.SaveRequest.FromString,
                    response_serializer=neurofly__pb2.SaveReply.SerializeToString,
            ),
            'Stimulate': grpc.unary_unary_rpc_method_handler(
                    servicer.Stimulate,
                    request_deserializer=neurofly__pb2.Selection.FromString,
                    response_serializer=neurofly__pb2.Count.SerializeToString,
            ),
            'Silence': grpc.unary_unary_rpc_method_handler(
                    servicer.Silence,
                    request_deserializer=neurofly__pb2.Selection.FromString,
                    response_serializer=neurofly__pb2.Count.SerializeToString,
            ),
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=neurofly__pb2.Selection.FromString,
                    response_serializer=neurofly__pb2.Count.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=neurofly__pb2.Empty.FromString,
                    response_serializer=neurofly__pb2.Ack.SerializeToString,
            ),
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=neurofly__pb2.Selection.FromString,
                    response_serializer=neurofly__pb2.Indices.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neurofly.NeuroFly', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neurofly.NeuroFly', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NeuroFly:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Info',
            neurofly__pb2.Empty.SerializeToString,
            neurofly__pb2.InfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Reset',
            neurofly__pb2.Empty.SerializeToString,
            neurofly__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Step',
            neurofly__pb2.StepRequest.SerializeToString,
            neurofly__pb2.StepReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Observe',
            neurofly__pb2.StepRequest.SerializeToString,
            neurofly__pb2.StepReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/neurofly.NeuroFly/Stream',
            neurofly__pb2.StepRequest.SerializeToString,
            neurofly__pb2.StepReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BodyStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/BodyStep',
            neurofly__pb2.BodyRequest.SerializeToString,
            neurofly__pb2.BodyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BodyStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/neurofly.NeuroFly/BodyStream',
            neurofly__pb2.BodyRequest.SerializeToString,
            neurofly__pb2.BodyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/SetPolicy',
            neurofly__pb2.Policy.SerializeToString,
            neurofly__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Save',
            neurofly__pb2.SaveRequest.SerializeToString,
            neurofly__pb2.SaveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stimulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Stimulate',
            neurofly__pb2.Selection.SerializeToString,
            neurofly__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Silence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Silence',
            neurofly__pb2.Selection.SerializeToString,
            neurofly__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Probe',
            neurofly__pb2.Selection.SerializeToString,
            neurofly__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Clear',
            neurofly__pb2.Empty.SerializeToString,
            neurofly__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurofly.NeuroFly/Select',
            neurofly__pb2.Selection.SerializeToString,
            neurofly__pb2.Indices.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
